### PR TITLE
Add breton language

### PR DESCRIPTION
**Pull request by ewenak**
Implement support for breton language (brezhoneg).

In breton (regional language spoken in western part of France), the alphabet looks like the latin alphabet, but there are no c, q and x, and there are two special entities considered as single letters: "c'h" and "ch". To accomodate this, I transliterate c'h to q and ch to c in the dictionaries files, and do the reverse mapping on display, through the existing `toDisplay` method and I had to introduce a new method `toRepresentation`, to do the reverse mapping in wordlist display.

### CODE REVIEW

**Comment by pserwylo** [comment]
Oh wow, thanks for this, sorry I didn't notice it earlier. I'll try to get time to look over it, give it a quick test out, and then if all is well, get a release out in the next week or two. Will update here as I go.

**Comment by pserwylo** [comment]
Looking good. The transliteration stuff is cool and something that others may find useful too, thanks for adding. Unfortunately it falls over when viewing words containing any of these characters with the following:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.serwylo.lexica, PID: 7221
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at com.serwylo.lexica.activities.score.MissedWordsViewBinder.onViewWord(MissedWordsViewBinder.java:78)
        at com.serwylo.lexica.activities.score.MissedWordsViewBinder.lambda$6r1UfX1iRlBEYTi65aA1yTNXGRs(Unknown Source:0)
        at com.serwylo.lexica.activities.score.-$$Lambda$MissedWordsViewBinder$6r1UfX1iRlBEYTi65aA1yTNXGRs.onViewWord(Unknown Source:2)
        at com.serwylo.lexica.activities.score.ScoreWordsViewBinder$ViewHolder.lambda$bind$1(ScoreWordsViewBinder.java:173)
        at com.serwylo.lexica.activities.score.-$$Lambda$ScoreWordsViewBinder$ViewHolder$p8gAH1k77Qdm1I8hiEcCLrGczeU.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Which is the following:

```
    private void onViewWord(String word) {
        boardView.highlight(game.getSolutions().get(word).get(0).getPositions());
```

The `word` argument contains `c'h` but the `game.getSolutions()` expects a `q` (I think).

**Comment by ewenak** [comment]
Thanks for testing it thoroughfully! I indeed stored the representation in the word lists. I just fixed that by calling toRepresentation only on display, so that the stored string is always the transliterated one.

**Comment by pserwylo** [comment]
Apologies for the slow response here. Life took over and then the Lexica build broke (due to the closure of the jcenter repository). I have since found time to get the build working again, and will merge this now. I'll see if there are any other PRs to add to this release, do a bit of testing, but if all is well then we should be able to cut a release with this included in the next week or two. Thanks again!

**Comment by pserwylo** [comment]
Just doing some cursory testing prior to release. Note that the `C'H` tile doesn't quite fit. I'm not too fussed by it, it still seems to be playable at least, and we can think of another solution down the track of need be, but just wanted to let you know.

We could just shrink the font a little bit, but that wouldn't be a permanent solution for all possible languages for which `toRepresentation(character)` could be used - some may have larger text requriements, some smaller. For now,  happy to release like this.

image

**Comment by ewenak** [comment]
Thanks for the merge, and for noticing this, I just checked, it can be improved by using C'h / Ch, like what is done with Qu in english. The toDisplay method has to be adapted too. I will do another PR with this fix.

**Pull request merged**
