### PR TITLE
Add Chinese transaltion

### PR DESCRIPTION
**Pull request by osfans**

### CODE REVIEW

**Comment by pserwylo** [comment]
Hi @osfans, thanks you very much for the translations. Sorry I hadn't extracted all the strings, I didn't expect such a contribution so quickly :)

**Comment by pserwylo** [comment]
I've bumped the version number and tagged a release, so F-Droid should pick it up next time it runs a build (in a day or two) with the translations. Thanks again!

**Comment by osfans** [comment]
You merged so quicky!

I want to do a similar Chinese game, but there are thousands of Chinese characters rather than 26 latin letters.

It seems that Trie doesn't work in Chinese case?

**Comment by pserwylo** [comment]
Based on my reading, the Trie class is hard coded to know about US + UK. I think in the future when I get some time, I'd like to make it so that instead of a single `res/raw/words.bin` file, there is a `res/raw/words.en_US.bin` and `res/raw/words.en_UK` file. Then the Java code can decide which `words.bin` to use depending on the preference that specifies the dictionary to use. This should then make it easier to add new dictionaries, although there will also need to be some sort of knowledge about what characters are allowed. Perhaps an initial iteration over the entire trie (if it is not too processor intensive) could enumerate all of the characters that are possible. The only catch then would be the English "Q" which is always shown as "Qu". Maybe some extra metadata specifying the allowed characters, and the ones which always go together like with "Qu".

Either way, it is a non trivial thing to do, but will be worth it in the long run. However I haven't read the trie code very throroughly yet.

**Comment by osfans** [comment]
Separated bin file is better. Or even, users could  import their own dictinary files.

I'll try to test Chinese word puzzle in PC first. 
Maybe it's unplayable or tedious, since there are so many characters and so few words.

**Pull request merged**
