### PR TITLE
German translation.

### PR DESCRIPTION
**Pull request by residuum**

### CODE REVIEW

**Comment by pserwylo** [comment]
Thanks @residuum, much appreciated! I'll try and do a release with these translations over the next few days.

**Comment by pserwylo** [comment]
@residuum - I've tagged v0.9.3, should be built and released on F-Droid next time the build server checks for updates. I've also requested an account at https://hosted.weblate.org because the first two merge requests were translations, and Weblate will be able to give the project a few nice features with regard to translations rather than only ever accepting merge requests for `strings.xml`.

Thanks again.

**Comment by pserwylo** [comment]
FYI, this has now been released as 0.9.3 on F-Droid:
https://f-droid.org/repository/browse/?fdfilter=lexica&fdid=com.serwylo.lexica

**Comment by residuum** [comment]
Thank you.

**Pull request merged**
