### PR TITLE
Added Hungarian dictionary.

### PR DESCRIPTION
**Pull request by urbalazs**
Hello @pserwylo 

I tried to create the Hungarian dictionary for the game, but I couldn't generate the "letters_hu.txt" file, because grade always failed with an exception. Can you help me to generate the missing file for this PR?

I sorted the existing languages to alphabetical order for better reading.

About the wordlist:
There is a repo with the Hungarian dictionary: https://github.com/laszlonemeth/magyarispell/
The wordlist was generated from this repo with the following command:
`git grep -E '^[a-zöüóőúéáűí]{4,9}($|\b)' -- szotar | cut -d ':' -f 2 | grep -Eo '^[a-z]*'  | sort | uniq  > dictionary.hu.txt`

Regards,
Balázs

### CODE REVIEW

**Comment by pserwylo** [comment]
Sure, I'll go have a look. If you have any further info on the Exception it would be great to hear it. Perhaps a memory exception? Anyway, the `./gradlew analyseLanguage_hu` script is running without error for me, I just need to run it a whole bunch of times so that we can get a good letter distribution. So far after about 5 runs (of the script, which means about 25 runs of the genetic algorithm) I have a distribution which produces the following number of words:

 * The worst board had 1.
 * The average number of words is 23
 * The maximum number of words is 56

This is not particularly good yet. Typically other languages average about 75 words, a minimum of 30 words, and a maximum of 200-400. I'll report back after a few more runs.

**Comment by urbalazs** [comment]
Hello @pserwylo 
I investigated, why does Hungarian dictionary contain less words. The dictionary was built from a Hungarian dictionary, and the words were filtered out with less than 4 and more then 9 letters. This dictionary doesn't contain more forms, so there are no plural forms, no genitive, etc.
I checked the other dictionaries, and they contain the words in more forms. For example in the en_US dictionary there are:

- civil
- civilian
- civilians
- civility
- civilize
- civilized
- civilizer
- civilizes
- ...

And this dictionary also contains 3-letter words, like cat, dog, etc. , 1205 words with 3 letter:
```
grep -E '^.{3}($|\b)' dictionary.en_US.txt | wc -l
1205
```

So that is the reason, why is my dictionary smaller then the others. Shall I add also the 3-letter words?

**Comment by pserwylo** [comment]
Great, thanks @urbalazs.

Adding 3 letter words would be good, because on a smaller (4x4 board) Lexica allows 3 letter words. 5x5 boards only allow 4 letter words and larger, and 6x6 boards only allow 5 letter words or larger. Could you please make that change and update this PR, then I'll re-generate the letter distribution. It sounds like it is okay that there are less words in the Hungarian dictionary for now, and we can address it if it becomes a problem in the future.

**Comment by urbalazs** [comment]
Hello @pserwylo 
Can you check again my pull request?

**Comment by pserwylo** [comment]
Thanks for the reminder @urbalazs. Change looks good. Unfortunately I think I need to regenerate the `letters` file, but I can do that over night, and hopefully merge this over the coming days and do another release with your changes.

**Comment by urbalazs** [comment]
Hello @pserwylo 
Did you manage to regenerate the letters?

**Comment by pserwylo** [comment]
Alrighty, sorry for the delay. I've added the relevant file, and also fixed a small bug introduced in this branch. It is available in #99 which I'll merge once CI passes. After that, I will perform some further testing, and then create a release with this branch. Thanks again for your patience.

**Pull request merged**
