### PR TITLE
Add Brazilian Portuguese dictionary

### LINKED ISSUE #127: Add Brazilian Portuguese (pt_BR) dictionary
Running `./add-lang.sh pt_BR` (passing 1 argument, note the underscore) works just fine. But when following the instructions in `assets/dictionary/README.md` to run `./add-lang.sh pt BR` (passing 2 arguments), it fails to read the correct file path and generates an empty dictionary. The following output is displayed:
```
lexica$ LC_ALL=C ./add-lang.sh pt BR
Error: The language "pt" is not known. This is probably because: the file "/usr/lib/aspell-0.60/pt.dat" can not be opened for reading.
Wrote assets/dictionaries/dictionary.pt_BR.txt
```
The directory's contents are:
```bash
$ ls -1 /usr/lib/aspell-0.60/pt*
/usr/lib/aspell-0.60/pt_BR_affix.dat
/usr/lib/aspell-0.60/pt_BR.dat
/usr/lib/aspell-0.60/pt_BR.multi
/usr/lib/aspell-0.60/pt_BR.rws
/usr/lib/aspell-0.60/pt_PT_affix.dat
/usr/lib/aspell-0.60/pt_PT.dat
/usr/lib/aspell-0.60/pt_PT.multi
/usr/lib/aspell-0.60/pt_PT-preao_affix.dat
/usr/lib/aspell-0.60/pt_PT-preao.dat
/usr/lib/aspell-0.60/pt_PT-preao.multi
/usr/lib/aspell-0.60/pt_PT-preao_repl.dat
/usr/lib/aspell-0.60/pt_PT-preao.rws
/usr/lib/aspell-0.60/pt_PT_repl.dat
/usr/lib/aspell-0.60/pt_PT.rws
```

**Environment:**
distro: Arch Linux 64-bit
packages:
- aspell 0.60.8-1
- aspell-pt 20161001-1

### PR DESCRIPTION
**Pull request by rffontenelle**
_**NOTE:** commits are separated for better preview, but let me know and I'll squash 'em into a single one._

Applying steps from [assets/dictionaries/README.md](https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md):
* [x] Add a dictionary file - `./add-lang.sh pt_BR`
* [x] **Make Gradle aware of the language** - Add `"pt_BR",` to the `languages` array in `build.gradle`
* [x] **Generate a trie representation of the dictionary** - `./gradlew buildDictionary_pt_BR`
* [x] **Add subclass PortugueseBR `Language`** to the `libraries/trie` library
* [x] **Tell Lexica about your `Language` class** - Add an entry to `Language#getAllLanguages()`
* [x] **Generate random letter distributions** - `./gradlew analyseLanguage_pt_BR` (saves distributions to `/tmp`)
* [x] **Choose "best" distribution** - Typically the highest "score", but boards with low min or median scores are generally poor)
* [x] **Rename the distribution file to `letters_LANG.txt`**, `letters_de_br.txt`
* [x] **Copy to project** - The renamed file should exist in `app/src/test/resources/` and `app/src/main/res/raw/`
* [x] **Add language name (in English)** - Edit `donottranslate.xml`, adding to `dict_choices_entryvalues` and `dict_choices_entries` (the latter will also require an entry in `strings.xml`)
* [x] **Add scrabble scores** - Edit your `Language` subclass, adding letter scores from [Wikipedia - Scrabble letter distributions](https://en.wikipedia.org/wiki/Scrabble_letter_distributions)
* [x] **Run tests** - `./gradlew check && ./gradlew connectedCheck`

Last step returned errors which seemed to be unrelated to my dictionary. See complete log: 
[check-log.txt](https://github.com/lexica/lexica/files/4628472/check-log.txt)

Closes #127

### CODE REVIEW

**Comment by pserwylo** [comment]
Thanks for your work on this, looking very good. I've added a couple of commits on top to finialize this, can you please cherrypick them from my `pserwylo/lexica` fork (`add_pt_BR` branch)? Then this should be good to merge.

The earlier version of the language analysis thing was badly behaved in that it put a line at the top of the letters file so that it is non-parsable. The newer version now understands comments, and puts some information at the top to explain the file:

https://github.com/pserwylo/lexica/commit/6b5bb2873a7bfff2807448e1ec53fe961bb2036f

```
#
# pt_BR language letter distributions for Lexica
#
# Automatically generated by a genetic algorithm run with 1000 iterations
#  - Each iteration, 100 4 x 4 Lexica boards were generated.
#  - The fitness function looks at how many words can be played on each of these boards.
#  - Fitness is defined as "(Mean * Mean) - (Standard Deviation * Standard Deviation).
#
# The goal is boards that on average have a high number of words available (boards with zero or only a small number of words are not good),
# but the standard deviation is low (some languages tend to result in boards with hundreds of words, which is also not particularly great).
#
# Fitness for this probability:
#   Min: 31, mean: 165, max: 518, stddev: 98, score: 17597
#
```

Also need to add three more letters to the letter-points section, or else it will crash when these letters are shown on a board with the "Letter Points" score type:

https://github.com/pserwylo/lexica/commit/b767b91d9588ec222bb45fae1b8cd7af3d5c050c

**Comment by rffontenelle** [comment]
Cherry-picked. ✓

**Comment by pserwylo** [comment]
Thanks for your work on this. Typically we wait a bit, maybe a week, before releasing so the new string can be translated, then I'll push a new version, then F-Droid will build and then release it. I'll keep you posted.

**Comment by rffontenelle** [comment]
No problem. Thanks for merging it.

**Comment by rffontenelle** [comment]
@pserwylo Hey there. Not to put pressure or anything, but I didn't see a new release. Is it on your plans?

**Comment by rffontenelle** [comment]
@pserwylo You for sure have a great reason for the absence! Congratulation, by the way, and thanks a lot for the release!

**Pull request merged**
