### PR TITLE
Add Finnish language

### PR DESCRIPTION
**Pull request by dancek**
Add the Finnish dictionary from the governmental linguistic institute of Finland, available under the CC-BY license. A script for fetching and generating the dictionary is included.

The letter distribution data was the best in about a dozen runs in terms of minimum and mean, and second best in terms of score.

### CODE REVIEW

**Comment by pserwylo** [comment]
This is great, thanks for the contribution. I especially appreciate the attention to detail regarding licences and the build script for the wordlist, but also the definition URL, etc. 

Regarding the distribution, that algorithm is really just my best effort at producing "fun" distributions (for whatever criteria we consider to be "fun" - e.g. not too many or too few words per board). My question to you is: are you happy after a couple of plays that this distribution is fun? Of course based on your completely subjective gut feel. 

If so, then lets change the `isBeta` flag in the `Language` class for Finnish to `false`. That flag was really only for when I, as mono-lingual-English-speaker, implemented a language on behalf of others. I had no way to verify myself whether it was actually any good. Given (I assume 😁) you speak Finnish, lets call this complete and non-beta.

**Comment by dancek** [comment]
Good to hear!

I'll give this a couple of days of playtesting and get back to you once I'm ready to call it non-beta. One thing that strikes me is that letters like C, W and G tend not to have any words using them in a 4x4 grid, even though they're kinda usable in Scrabble. I might rework the dictionary to exclude letters that are only present in rare loanwords. Other than that, the boards I've seen seem good.

**Comment by pserwylo** [comment]
Thanks. Ping me here when you are happy with it, and I'll merge and release.

**Comment by pserwylo** [comment]
Or do you want me to release this now with the beta flag set, and when you are happy, file another PR to get it out of beta?

**Comment by dancek** [comment]
Either is fine by me. Probably easier for you if I ping you in a couple of days?

**Comment by pserwylo** [comment]
Great, I'll keep an eye out.

**Comment by dancek** [comment]
I'm happy with how it plays after this new commit. I removed C and W which are "less Finnish" than the other letters.

Feel free to merge and release this!

**Comment by pserwylo** [comment]
Thanks for taking that feedback on, tidying up, and letting me know. I'll merge now, and *prepare* a release, but will wait a couple of days. There is one release with misc bugfixes in the F-Droid build pipeline right now. I shamelessly like to get a release into as many F-Droid updates as possible so that we bubble to the top of the recently updated list (both on the main page and also in the game category) frequently. I've noticed this increases the number of contributions / issue reports / translations from the community which is nice ;)

Once this last one is out, I'll tag this for release.

**Pull request merged**
