### PR TITLE
Spanish language without accents but with Ntilde

### PR DESCRIPTION
**Pull request by jgmy**
Hi!

In Spain, the game "Boggle" and "Scrabble", their clones (such as "Intelect") and most word games do not use the accented vowels, but use Ñ (n-tilde).

The reason is that, in Spanish, accented letters do not "sound" different, but mark the stressed vowel in a word, thus Spanish words have between zero and one accented vowel. In the other hand, ñ  has its own sound (like ni in "Welcome to the hotel Califor**ni**a" or gn in  "I ate some **gn**occhi").

The case for Ü is different. I think Intelect (a Scrabble clone made by Cefa in the early eighties) included it. But most word games (crosswords and word search puzzle) don't. ISO 676-es included Ñ (N tilde) and some accented letters, but did not accept Ü (U umlaut). And, up to around 2010 my digital certificate issued by Spanish government failed in most Spanish government agencies just because it included an unsupported Ü (U umlaut).

So I have developed a Spanish language with Ñ and without áéíóú. It does not include ü.

I have tested it on my mobile device (gradlew installAndroid). Please notice IT DOES NOT PASS gradlew check (messages about errors with Persian appear). As the issues appear in files I did not modify, I think this version is *slightly* sure.

Dictionary used was the original dictionary_es.txt (which still includes some buggy words, unsolved issue) passed by a sed filter. The sed script used, and shell scripts, are included. Please notice I could not use the shell scripts, since "sort" was sorting with C-style regardless of LOCALE set to es_ES (I was on mingw on windows).

### CODE REVIEW

**Comment by jgmy** [comment]
Please, wait. I discovered a bug. Maybe it comes from the fact I compiled on a windows console, but I have to analyze it.

Screenshot_20210803-162225_Lexica


I guess "?" should be a Ñ.

I revised the letters distribution files and they seem to be OK. I will try to recompile and then I will tell you.

**Comment by jgmy** [comment]
Please use second commit. Now all characters work.

I don't understand why the letters file was generated as ISO-8859-1 by the script. Maybe I had that codepage when I ran the letters script.

BTW I had to tune the script, since it uses ":" in file names, and MSWindows is angry about that. If you want to see my modified version, I can make a pull request about that.

**Comment by jgmy** [comment]
WARNING! Spanish letter score is broken in my version. I don't know why, since I did not change it.

**Comment by jgmy** [comment]
Hi.
**testPersian still fails.**
testUnicodeLetters now **works**.
gradle.build gives errors at the letterScoreTest. Please notice **no error** was given on previous commit of this branch, where score mode **crashed** (accented letters were given no score due default javac encoding being different on windows).
The app works.

I have added a encoding option at top build.gradle to make life beautiful for windows users.

**Comment by pserwylo** [comment]
Thanks so much for this contribution @jgmy. Really great to see native speakers contributing alternative dictionaries like this. I especially appreciate the detailed comments in your scripts explaining why you made certain choices regarding this dictionary.

The tests are passing in GitHub Actions (and also on my local Linux machine) so this is good to go. I'll merge now, wait for the previous version to be built by F-Droid (translation updates) then bump a v2.6.0 with this new dictionary. Will post here as that progresses to keep you informed.

Thanks again.

**Comment by jgmy** [comment]
Many thanks.

Atentamente,
José G. Moya Y.

P.D. Escribo desde un móvil. Disculpe posibles erratas.

**Pull request merged**
