### PR TITLE
WIP: Implement sorting modes for "missed words" end game screen #101

### LINKED ISSUE #101: Feature request: Sort "missed words" by length
Would it be possible to enable sorting by length of word in the "Missed words" list?  Thanks!

### PR DESCRIPTION
**Pull request by gsheridansmith**
I've never done any android development before and I'm not sure what I'm supposed to about the translations, but this should fix #101 

Happy to try and add anything extra that's needed

### CODE REVIEW

**Comment by pserwylo** [comment]
Hey, that is great, thanks so much. How do you feel about me taking the aspect to do with actually sorting the lists, but remove the preference and replace it with a toggle button on the score page?

I'm keen to reduce the amount of preferences over time, and think that allowing sorting from within the score list is probably a good user experience too.

If you're keen to continue playing with Android code, happy for you to give it a crack. Alternatively, I'm happy to chip in as well. In fact, I must admit I started building on top of your code without first reading your "Happy to try and add anything extra that's needed", so I'll pause and let you take back over if you wish.

This is where I got to:

image
image

Just the UI, not connected to any logic yet:

```
diff --git a/app/src/main/res/layout/score_found_words.xml b/app/src/main/res/layout/score_found_words.xml
index a7db49f..8036acd 100644
--- a/app/src/main/res/layout/score_found_words.xml
+++ b/app/src/main/res/layout/score_found_words.xml
@@ -4,7 +4,8 @@
 	android:layout_width="match_parent"
 	android:background="?attr/score__background_colour"
 	xmlns:app="http://schemas.android.com/apk/res-auto"
-	xmlns:tools="http://schemas.android.com/tools">
+	xmlns:tools="http://schemas.android.com/tools"
+	xmlns:fancy="http://schemas.android.com/apk/res-auto">
 
 	<androidx.constraintlayout.widget.ConstraintLayout
 		android:id="@+id/score_wrapper"
@@ -77,13 +78,19 @@
 
 	</androidx.constraintlayout.widget.ConstraintLayout>
 
+	<include layout="@layout/score_sort_button"
+		android:layout_height="wrap_content"
+		android:layout_width="wrap_content"
+		app:layout_constraintEnd_toEndOf="parent"
+		app:layout_constraintTop_toBottomOf="@id/score_wrapper" />
+
 	<androidx.recyclerview.widget.RecyclerView
 		android:id="@+id/words"
 		android:layout_width="0dp"
 		android:layout_height="0dp"
 		app:layout_constraintStart_toStartOf="parent"
 		app:layout_constraintEnd_toEndOf="parent"
-		app:layout_constraintTop_toBottomOf="@id/score_wrapper"
+		app:layout_constraintTop_toBottomOf="@id/btn_sort"
 		app:layout_constraintBottom_toBottomOf="parent"
 		tools:listitem="@layout/score_summary_word"
 		android:scrollbars="vertical" />
diff --git a/app/src/main/res/layout/score_missed_words.xml b/app/src/main/res/layout/score_missed_words.xml
index 7227b16..b2fd85b 100644
--- a/app/src/main/res/layout/score_missed_words.xml
+++ b/app/src/main/res/layout/score_missed_words.xml
@@ -26,6 +26,12 @@
 			app:layout_constraintStart_toStartOf="parent"
 			app:layout_constraintBottom_toBottomOf="parent" />
 
+		<include layout="@layout/score_sort_button"
+			android:layout_height="wrap_content"
+			android:layout_width="wrap_content"
+			app:layout_constraintEnd_toEndOf="parent"
+			app:layout_constraintBottom_toBottomOf="parent" />
+
 	</androidx.constraintlayout.widget.ConstraintLayout>
 
 	<androidx.recyclerview.widget.RecyclerView
diff --git a/app/src/main/res/layout/score_sort_button.xml b/app/src/main/res/layout/score_sort_button.xml
new file mode 100644
index 0000000..ca8e369
--- /dev/null
+++ b/app/src/main/res/layout/score_sort_button.xml
@@ -0,0 +1,22 @@
+<?xml version="1.0" encoding="utf-8"?>
+<mehdi.sakout.fancybuttons.FancyButton
+	xmlns:android="http://schemas.android.com/apk/res/android"
+	xmlns:fancy="http://schemas.android.com/apk/res-auto"
+
+	android:id="@+id/btn_sort"
+	android:layout_width="wrap_content"
+	android:layout_height="wrap_content"
+	android:text="Sort"
+	android:layout_margin="?attr/game__score__padding"
+	fancy:fb_fontIconResource="&#xf15d;"
+	fancy:fb_fontIconSize="14sp"
+	fancy:fb_radius="12dp"
+	fancy:fb_iconPaddingLeft="8dp"
+	fancy:fb_iconPaddingRight="8dp"
+	fancy:fb_iconPaddingTop="8dp"
+	fancy:fb_iconPaddingBottom="8dp"
+	android:paddingRight="8dp"
+	android:paddingEnd="8dp"
+	fancy:fb_defaultColor="?attr/home__secondary_button_background"
+	fancy:fb_focusColor="?attr/home__secondary_button_background_focused"
+	fancy:fb_textColor="?attr/home__secondary_button_text_colour" />
```

FYI - for someone who hasn't done androi development before, you sure dived right into the quirky parts of the Android API here - `ViewBinder`, `ViewHolder`, etc - it isn't the most elegant API going around :smiley:.

**Comment by gsheridansmith** [comment]
Adding the sort mode to the actual missed words screen to change ad-hoc is definitely a better UX. If this PR was missing something blindingly obvious but simple, I'd happily fix it but honestly you're probably much better placed to implement the change if you've got something decent going
The extent of my Android experience is the hour or so it took to put this PR together, I'm a back-end dev by day so I wouldn't even know where to start hooking things into a GUI

Thanks for taking a look!

**Comment by gsheridansmith** [comment]
Adding the sort mode to the actual missed words screen to change ad-hoc is definitely a better UX. If this PR was missing something blindingly obvious but simple, I'd happily fix it but honestly you're probably much better placed to implement the change if you've got something decent going
The extent of my Android experience is the hour or so it took to put this PR together, I'm a back-end dev by day so I wouldn't even know where to start hooking things into a GUI

Thanks for taking a look!

**Comment by gsheridansmith** [comment]
Adding the sort mode to the actual missed words screen to change ad-hoc is definitely a better UX. If this PR was missing something blindingly obvious but simple, I'd happily fix it but honestly you're probably much better placed to implement the change if you've got something decent going
The extent of my Android experience is the hour or so it took to put this PR together, I'm a back-end dev by day so I wouldn't even know where to start hooking things into a GUI

Thanks for taking a look!

**Comment by pserwylo** [comment]
Alrighty, all done, thanks for your contribution @gsheridansmith. I'll let this sit in `master` for a bit before releasing, because it has a new translation associated with it. Normally I leave for about a week for the wonderful translation community to provide an updated translation. Feel free to check it out yourself in the meantime though, any feedback welcome.

**Pull request merged**
